version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  setup:
    docker:
      - image: cimg/node:14.18.0-browsers
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run: node --version
      - run: yarn --version

workflows:
  ci:
    jobs:
      - setup
