version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  setup:
    docker:
      - image: cimg/node:14.18.0-browsers
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node --version
      - run: yarn --version

workflows:
  ci:
    jobs:
      - setup
