version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  setup:
    docker:
      - image: circleci/node:14.18.0-browsers
    steps:
      - checkout
      - node/install:
        install-yarn: true
      - run: node --version
      - run: yarn --version

workflow:
  ci:
    - setup
